### ISSUE TITLE
from transformers import Tool ModuleNotFoundError: No module named 'transformers'

### ISSUE THREAD

**Issue by JayyShah** [build-on-aws/building-gen-ai-agent-on-aws#2]
I encountered an issue while working with the transformers library in Python. Specifically, when trying to import the Tool class from the transformers module, I received the following error:

`ModuleNotFoundError: No module named 'transformers'` 

I have already installed the transformers library  and I can confirm that it is present in my environment. However, the import statement for the Tool class is still causing the error.

I have also tried other variations, such as importing Tool directly from transformers.tools, but the error persists.

Could you please provide some guidance on resolving this issue? I have verified the installation and confirmed that the module is present, but it is still not being recognized during import.

Thank you for your assistance.

**Comment by cjamtp** [comment]
Do you use conda ?

**Comment by JayyShah** [comment]
> Do you use conda ?

Yes it Worked, Thank you.
